services:
  - type: web
    name: n8n-rubyhustle
    env: docker
    repo: https://github.com/RubyHustle/n8n-deploy-clean
    branch: master
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: RubyHustle
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Rubin9626@
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
